### ISSUE TITLE
Sleep Graph

### ISSUE THREAD

**Issue by npcwoody** [jlai/fitness-dashboard#13]
The Sleep Graph does not show Wed. It shows Thu twice.

**Comment by chrissard2** [comment]
I also have twice on 9, 4, 2. for July, in June 6th twice.  I do not seem to be missing any days.  I looked back on my phone and I am not seeing any duplicates there.

**Comment by jlai** [comment]
Thanks for reporting! The graph probably needs to add up the sleep times for each day (it assigns sleep to the wakeup day, will need to check what the Fitbit app does)

**Comment by npcwoody** [comment]
For me it shows: Mon - Tue - Thu - Thu - Fri - Sat - Sun

**Comment by jlai** [comment]
Can you check how it looks now? I don't use sleep logging most of the time so I don't have much real data on my own account

**Comment by npcwoody** [comment]
Looks better now.  I will keep an eye on it and tell you if I have any more issues.

**Comment by chrissard2** [comment]
It also looks correct now.  Thanks

**Comment by dhdurgee** [comment]
I would also like to see last night's sleep time on the dashboard.

**Comment by jlai** [comment]
I added a sleep tile to the dashboard. if it doesn't show up, you may need to Edit Grid -> Add Tile -> Sleep

**Comment by chrissard2** [comment]
That works thanks

**Comment by jlai** [comment]
I redesigned the sleep history page a bit. It should hopefully be easier to read now. If your device supports sleep stages (REM/light/deep) you can click on a sleep log or the dashboard tile to view the hypnogram (sleep stage graph).
