### ISSUE TITLE
Add food to Favorites List

### ISSUE THREAD

**Issue by michae1a1ee** [jlai/fitness-dashboard#39]
I don't see an ability to do this.  Is it possible?

**Comment by jlai** [comment]
Go to Foods -> Favorites (link on right hand side) -> search for a food in the search box -> add favorite food

**Comment by michae1a1ee** [comment]
Thank you.
The process is not as simple as just picking and adding to the favorites list from the current day's food log or a recently logged food item, but at least the function is possible by re-searching for the item and adding it as you described.  Thanks again.

**Comment by jlai** [comment]
I've added a menu item (to the ... menu next to the delete/move/copy buttons) to add/remove foods from the food log to the favorites list.

**Comment by michae1a1ee** [comment]
Nice.  I see it.  Great usability improvement.
