### ISSUE TITLE
no heart rate data on some activities

### ISSUE THREAD

**Issue by speising** [jlai/fitness-dashboard#46]
On some of my activities (in particular, biking) there is no heart rate graph shown in the details, unless there's also a gps track.
the app shows the heart rate graph, the api delivers an url for it as well in the activity list.

**Comment by jlai** [comment]
Yeah when I wrote the code originally, I didn't have (approved) access to the intraday API so it just relied on the TCX heartrate data. I've added a fallback to grab the intraday heart rate for non-GPS-tracked activities.
