### ISSUE TITLE
Error loading server response (500)

### ISSUE THREAD

**Issue by npcwoody** [jlai/fitness-dashboard#74]
Yesterday a new update to the Fitbit app on my phone automatically updated. This morning I have an error code in most of the fields on your dashboard: "Error loading server response (500)" Please help.

**Comment by jlai** [comment]
Unfortunately this is a problem on Fitbit's servers so I'm not sure if there's anything we can do other than wait and hope they fix it. Please let me know if the problem continues or if anyone else is seeing this issue (I don't see it for my own account, but there seem to be widespread problems with the 3rd party API and the apps). Sorry.

**Comment by jlai** [comment]
Are you still seeing this issue?

**Comment by npcwoody** [comment]
I'm sorry. The issue went away after two days.

**Comment by jlai** [comment]
Ah, great to hear it's been working for you. Thanks for the update.
