### ISSUE TITLE
Activity Logs

### ISSUE THREAD

**Issue by tuunccelik** [jlai/fitness-dashboard#75]
Activity Logs data under History section is empty for me. I use the dashboard for about 2 weeks. It is same from the first day.
![Screenshot_20240922_200027_Edge](https://github.com/user-attachments/assets/d297c03a-dbdf-40f2-b5e2-7f63a3f59a3f)

**Comment by jlai** [comment]
I'm guessing you can see the activities in the Fitbit app (Today -> Exercise Days ->Week/Month)? There's probably something weird going on with Fitbit's servers.

I've heard people report the opposite, where they can see exercises on this web dashboard but not on the app. Nobody has any idea what's going on but hopefully Fitbit is looking into it.

**Comment by tuunccelik** [comment]
Hey Jlai! I am also not able to see the activities in the Fitbit app (Today -> Exercise Days ->Week/Month). Wait and will see what will happen. Thanks! Have a great day!
